// Generated by gencpp from file yolo/NamedPoseArray.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_NAMEDPOSEARRAY_H
#define YOLO_MESSAGE_NAMEDPOSEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <geometry_msgs/Pose.h>

namespace yolo
{
template <class ContainerAllocator>
struct NamedPoseArray_
{
  typedef NamedPoseArray_<ContainerAllocator> Type;

  NamedPoseArray_()
    : names()
    , poses()  {
    }
  NamedPoseArray_(const ContainerAllocator& _alloc)
    : names(_alloc)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::String_<ContainerAllocator> >> _names_type;
  _names_type names;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::yolo::NamedPoseArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo::NamedPoseArray_<ContainerAllocator> const> ConstPtr;

}; // struct NamedPoseArray_

typedef ::yolo::NamedPoseArray_<std::allocator<void> > NamedPoseArray;

typedef boost::shared_ptr< ::yolo::NamedPoseArray > NamedPoseArrayPtr;
typedef boost::shared_ptr< ::yolo::NamedPoseArray const> NamedPoseArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo::NamedPoseArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo::NamedPoseArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo::NamedPoseArray_<ContainerAllocator1> & lhs, const ::yolo::NamedPoseArray_<ContainerAllocator2> & rhs)
{
  return lhs.names == rhs.names &&
    lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo::NamedPoseArray_<ContainerAllocator1> & lhs, const ::yolo::NamedPoseArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo::NamedPoseArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo::NamedPoseArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::NamedPoseArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::NamedPoseArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::NamedPoseArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::NamedPoseArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo::NamedPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d55d7c9033cda1a6709b27c7341d0b57";
  }

  static const char* value(const ::yolo::NamedPoseArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd55d7c9033cda1a6ULL;
  static const uint64_t static_value2 = 0x709b27c7341d0b57ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo::NamedPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo/NamedPoseArray";
  }

  static const char* value(const ::yolo::NamedPoseArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo::NamedPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String[] names\n"
"geometry_msgs/Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::yolo::NamedPoseArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo::NamedPoseArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NamedPoseArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo::NamedPoseArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo::NamedPoseArray_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.names[i]);
    }
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_MESSAGE_NAMEDPOSEARRAY_H
